import { TourStep } from '@/components/TourGuide';

export const toolsPageTourSteps: TourStep[] = [
  {
    id: 'welcome',
    title: '👋 Step 1 of 11: Welcome to TrustInn',
    description: `Welcome! Let's learn how to analyze your code for security issues in just a few simple steps.`,
    position: 'bottom',
  },
  {
    id: 'language-tabs',
    target: '[data-tour="language-tabs"]',
    title: '🔤 Step 2 of 11: Pick Your Language',
    description: `Choose the programming language you want to analyze: C, Java, Python, or Solidity.`,
    position: 'bottom',
    action: 'Click a tab to select your language.',
  },
  {
    id: 'input-mode',
    target: '[data-tour="input-mode"]',
    title: '📝 Step 3 of 11: How to Input Code',
    description: `Upload a file or write code directly in the editor.`,
    position: 'bottom',
    action: 'Choose Upload File or Write Code.',
  },
  {
    id: 'file-upload',
    target: '[data-tour="file-upload"]',
    title: '📂 Step 4 of 11: Upload Your Code',
    description: `Browse and select your code file, or load a sample program to get started.`,
    position: 'bottom',
    action: 'Upload a file or click Load Sample.',
  },
  {
    id: 'tool-selection',
    target: '[data-tour="tool-selection"]',
    title: '🛠️ Step 5 of 11: Select a Tool',
    description: `Pick a security analysis tool. Different tools work for different languages.`,
    position: 'bottom',
    action: 'Click the dropdown to see available tools.',
  },
  {
    id: 'tool-parameters',
    target: '[data-tour="tool-parameters"]',
    title: '⚙️ Step 6 of 11: Tool Settings (Optional)',
    description: `Adjust settings like analysis depth and time limit. Default values work fine for most cases.`,
    position: 'bottom',
    action: 'Customize if needed, or leave as default.',
  },
  {
    id: 'load-sample',
    target: '[data-tour="load-sample"]',
    title: '📚 Step 7 of 11: Try Sample Programs',
    description: `Don't have code? Load a sample to see how everything works.`,
    position: 'bottom',
    action: 'Click Load Sample to get started quickly.',
  },
  {
    id: 'execute-button',
    target: '[data-tour="execute-button"]',
    title: '▶️ Step 8 of 11: Run Analysis',
    description: `Click here to analyze your code. Results appear on the right.`,
    position: 'top',
    action: 'Select a tool first, then click Execute.',
  },
  {
    id: 'terminal-output',
    target: '[data-tour="terminal-output"]',
    title: '📺 Step 9 of 11: View Results',
    description: `See the analysis results and any errors or findings here.`,
    position: 'left',
    action: 'Scroll to see all results.',
  },
  {
    id: 'result-actions',
    target: '[data-tour="copy-output"]',
    title: '🎯 Step 10 of 11: Manage Results',
    description: `Copy, visualize, download, or clear your results. You can copy results to clipboard, view charts and graphs, download as PNG/TXT/ZIP, or clear to start fresh.`,
    position: 'top',
    action: 'Use these buttons to copy, chart, download, or clear results.',
  },
  {
    id: 'user-info',
    target: '[data-tour="user-info"]',
    title: '👤 Step 11 of 11: Your Account',
    description: `Check your plan type and remaining trial usage here.`,
    position: 'bottom',
    action: 'Click Session Info for more details.',
  },
  {
    id: 'completion',
    title: '🎉 All Done!',
    description: `You're ready! Just pick a language, upload code, choose a tool, and click Execute. That's it!`,
    position: 'bottom',
  },
];
